
import React from 'react';
import {
    LayoutTemplate, ShoppingCart, Video, Award, CheckCircle,
    Facebook, Search, Music, Share2, Mail, MessageCircle, MessageSquare,
    Clock, Tag, Globe, Phone, UserCheck, Database, Calendar, MonitorPlay,
    MousePointer2, Instagram, Youtube, ArrowDownCircle, FileText, HelpCircle,
    BadgeCheck, UserPlus, Library, GraduationCap, UserRound, CircleDollarSign,
    Clapperboard, Pin, Smartphone, Send, Gamepad2, Split, Infinity, Twitch, Smile,
    StickyNote, Download, CalendarDays, Radio, AppWindow, File, FormInput, ClipboardList, ListPlus,
    Zap, Rocket, Target, Users, Monitor, PlayCircle, Lock, Server, Store, ShoppingBag, Star, AlertTriangle, Eye, ShieldAlert
} from 'lucide-react';
import { NodeType, Language, Template } from './types';
import type { Node, Edge } from 'reactflow';

export const TRANSLATIONS = {
    pt: {
        heroTitle: "Sua Estratégia Merece\nMais que um Rabisco.",
        heroDesc: "Profissionalize seu planejamento. Transforme ideias soltas em mapas visuais organizados, prontos para apresentar, ensinar ou executar.",
        startFree: "Criar Meu Primeiro Mapa",
        watchDemo: "Ver Como Funciona",
        features: "Benefícios",
        pricing: "Planos",
        signIn: "Entrar",
        getStarted: "Começar Grátis",
        problemTitle: "Benefícios",
        problemDesc: "Por que escolher o FluxFunnel?",
        problem1Title: "Clareza Imediata",
        problem1Desc: "Veja toda sua estratégia em um único mapa visual.",
        problem2Title: "Planejamento Profissional",
        problem2Desc: "Pare de usar papel, quadro branco ou ferramentas improvisadas.",
        problem3Title: "Apresente e Ensine",
        problem3Desc: "Explique sua estratégia para clientes, sócios ou equipe em minutos.",
        problem4Title: "Mais Organização",
        problem4Desc: "Transforme ideias soltas em processos bem definidos.",
        solutionTitle: "O que é o FluxFunnel?",
        solutionDesc: "O FluxFunnel é um construtor visual de funis e estratégias, criado para quem precisa enxergar, organizar e explicar processos de marketing e vendas.",
        solution1Title: "Canvas Visual",
        solution1Desc: "Arrasta e solta sem códigos. Monte tudo visualmente.",
        solution2Title: "Sem Integrações Complexas",
        solution2Desc: "Foco 100% no planejamento visual e organização.",
        solution3Title: "Biblioteca Completa",
        solution3Desc: "Ads, Páginas, E-mail, WhatsApp e muito mais.",
        useCasesTitle: "Para Quem É?",
        useCase1Title: "Gestores e Donos",
        useCase1Desc: "Donos de negócios, Gestores de Marketing e Gestores Comerciais.",
        useCase2Title: "Prestadores de Serviço",
        useCase2Desc: "Agências, Consultores e Times de Vendas.",
        useCase3Title: "Educadores",
        useCase3Desc: "Produtores Digitais e Professores que precisam de didática.",
        howItWorks: "Como Funciona",
        howItWorksSub: "Do caos à ordem em passos simples.",
        step1Title: "1. Crie e Arraste",
        step1Desc: "Crie um novo mapa e arraste elementos (Ads, Páginas, WhatsApp) para o canvas.",
        step2Title: "2. Conecte os Fluxos",
        step2Desc: "Ligue os pontos para definir a jornada do cliente e visualize toda a estratégia.",
        step3Title: "3. Planeje e Execute",
        step3Desc: "Use the map to present, validate ideas or guide the implementation.",
        faqTitle: "Dúvidas Comuns",
        faq1Q: "É difícil de usar?",
        faq1A: "Não. O FluxFunnel foi criado para qualquer pessoa, mesmo sem conhecimento técnico. É intuitivo e 100% visual.",
        faq2Q: "Preciso integrar com alguma conta de anúncio?",
        faq2A: "Não. O foco é 100% no planejamento visual e organização. Sem configurações técnicas chatas ou integrações complexas.",
        faq3Q: "Quais os limites do plano grátis?",
        faq3A: "Você pode criar 1 projeto ativo, com até 20 elementos no fluxo e acesso aos ícones básicos.",
        ctaFinalTitle: "Organize Suas Ideias Hoje",
        ctaFinalDesc: "Crie sua conta gratuita e desenhe seu primeiro fluxo profissional em minutos.",
        ctaFinalBtn: "Começar Agora - É Grátis",
        upgradeSuccess: "Plano atualizado com sucesso! Aproveite os recursos Premium.",
        noCreditCard: "Sem cartão de crédito",
        freeTrialDays: "Plano Gratuito Vitalício",
        monthly: "Mensal",
        yearly: "Anual",
        simplePricing: "Planos Simples",
        mostPopular: "RECOMENDADO",
        pricingFreeFeat1: "1 Projeto Ativo",
        pricingFreeFeat2: "20 Elements no Fluxo",
        pricingFreeFeat3: "Ícones Básicos",
        pricingFreeFeat4: "Modo Apresentação",
        pricingFreeFeat5: "Suporte via Email",
        pricingFreeFeat6: "Modo Escuro & Claro",
        pricingProFeat1: "5 Projetos Ativos",
        pricingProFeat2: "100 Elementos no Fluxo",
        pricingProFeat3: "Biblioteca Completa",
        pricingProFeat4: "Notas & Anotações",
        pricingProFeat5: "Salvar Templates",
        pricingProFeat6: "Suporte Dedicado",
        pricingPremiumFeat1: "Projetos Ilimitados",
        pricingPremiumFeat2: "Elementos Ilimitados",
        pricingPremiumFeat3: "Colaboração em Equipe",
        pricingPremiumFeat4: "IA: Auditoria de Estratégia (Beta)",
        pricingPremiumFeat5: "Link de Compartilhamento",
        pricingPremiumFeat6: "Suporte Prioritário",
        planBtnFree: "Começar Grátis",
        planBtnPro: "Assinar Agora",
        planBtnPremium: "Falar com Vendas",
        footerProduct: "Produto",
        footerCompany: "Empresa",
        footerLegal: "Legal",
        footerTagline: "Onde grandes estratégias são desenhadas.",
        footerLinkBuilder: "Construtor",
        footerLinkSims: "Galeria",
        footerLinkIntegrations: "Ícones",
        footerLinkRoadmap: "Roadmap & Feedback",
        footerLinkAbout: "Sobre",
        footerLinkBlog: "Blog",
        footerLinkCareers: "Carreiras",
        footerLinkPrivacy: "Privacidade",
        footerLinkTerms: "Termos",
        footerRights: "FluxFunnel Inc.",
        startBuilding: "Comece a organizar agora.",
        testimonialsNav: "Para Quem É",
        faqNav: "Dúvidas",
        pricingNav: "Preços",
        featuresNav: "Beneficios",
        trafficSources: "Fontes de Tráfego",
        communication: "Comunicação",
        funnelPages: "Páginas do Funil",
        opsLogic: "Ops & Lógica",
        componentLib: "Biblioteca",
        dragElements: "Arraste para o canvas",
        projects: "Projetos",
        myProjects: "Meus Projetos",
        maps: "Mapas",
        team: "Equipe",
        upgrade: "Upgrade",
        settings: "Configurações",
        signOut: "Sair",
        editFunnel: "Editar Funil",
        present: "Apresentar",
        lastSaved: "Salvo às",
        save: "Salvar",
        unsavedChanges: "• Não Salvo",
        saved: "Salvo",
        noProjectSelected: "Nenhum projeto selecionado",
        backToProjects: "Voltar para Projetos",
        createMapTitle: "Criar Novo Mapa",
        projectName: "Nome do Projeto",
        cancel: "Cancelar",
        createMapBtn: "Criar Mapa",
        unsavedModalTitle: "Alterações não salvas",
        unsavedModalDesc: "Você tem edições pendentes no seu funil. O que deseja fazer antes de sair?",
        saveAndExit: "Salvar e Sair",
        discardChanges: "Descartar alterações",
        keepEditing: "Cancelar (Continuar editando)",
        projectsDesc: "Gerencie seus mapas e fluxos educacionais.",
        newProject: "Novo Projeto",
        createVisualShortcut: "Criar Novo Mapa",
        editedAt: "Editado em",
        elementsCount: "Elementos",
        openBtn: "Abrir",
        deleteBtn: "Excluir",
        noMapsCreated: "Nenhum mapa criado",
        startOrganizingNow: "Comece a organizar suas ideias agora mesmo.",
        createFirstProject: "Criar meu primeiro projeto",
        chooseTemplate: "Escolha um Modelo",
        blankCanvas: "Em Branco",
        blankCanvasDesc: "Comece do zero com um canvas limpo.",
        templateVSL: "Funil VSL",
        templateWebinar: "Funil de Webinar",
        templateTripwire: "Funil Tripwire",
        templateLaunch: "Lançamento Semente",
        saveAsTemplate: "Salvar como Template",
        myTemplates: "Meus Modelos",
        systemTemplates: "Modelos do Sistema",
        templateSaved: "Template salvo com sucesso!",
        manageAccount: "Gerencie sua conta, preferências e assinatura.",
        tabProfile: "Meu Perfil",
        tabPreferences: "Preferencias",
        tabPlan: "Planos e Faturamento",
        tabSecurity: "Segurança",
        tabNotifications: "Notificaciones",
        personalInfo: "Informações Pessoais",
        yourPhoto: "Sua Foto",
        photoDesc: "Isso será exibido no seu perfil.",
        saveChanges: "Salvar Alterações",
        saving: "Salvando...",
        appearanceLang: "Aparência e Idioma",
        darkMode: "Modo Escuro",
        darkModeDesc: "Alterne entre temas claro e escuro.",
        systemLang: "Idioma do Sistema",
        currentPlan: "Plano Atual",
        autoRenewal: "Renovação automática ativa",
        billingHistory: "Histórico de Faturamento",
        tableDate: "Data",
        tableDesc: "Descrição",
        tableAmount: "Valor",
        tableStatus: "Status",
        noBilling: "Sem histórico de cobranças (Plano Grátis)",
        paid: "Pago",
        accountSecurity: "Segurança da Conta",
        currentPwd: "Senha Atual",
        newPwd: "Nova Senha",
        confirmPwd: "Confirmar Nova Senha",
        updatePwd: "Atualizar Senha",
        dangerZone: "Zona de Perigo",
        deleteAccount: "Excluir Conta",
        deleteWarning: "A exclusão da sua conta é irreversível. Todos os seus mapas e dados serão perdidos.",
        companyName: "Nome da Empresa",
        jobTitle: "Cargo / Função",
        paymentMethod: "Método de Pagamento",
        cardEnding: "terminado em",
        expires: "Expira em",
        updateMethod: "Atualizar",
        usageLimit: "Uso do Plano",
        projectsUsed: "Projetos Criados",
        nodesUsed: "Elementos no Fluxo",
        upgradeToIncrease: "Fazer upgrade para aumentar limites",
        activeSessions: "Sessões Ativas",
        currentSession: "Este dispositivo",
        twoFactor: "Autenticação de Dois Fatores (2FA)",
        twoFactorDesc: "Adicione uma camada extra de segurança à sua conta.",
        enable: "Ativar",
        disable: "Desativar",
        marketingEmails: "E-mails de Marketing",
        marketingEmailsDesc: "Receba dicas, ofertas e novidades do produto.",
        securityEmails: "Alertas de Segurança",
        securityEmailsDesc: "Receba avisos sobre logins suspeitos.",
        welcomeBack: "Bem-vindo de volta",
        createAccount: "Criar Conta",
        enterDetails: "Insira seus dados abaixo",
        fullName: "Nome Completo",
        emailAddr: "E-mail",
        password: "Senha",
        dontHaveAccount: "Não tem uma conta?",
        alreadyHaveAccount: "Já tem uma conta?",
        starter: "Grátis",
        pro: "Pro",
        agency: "Premium",
        forever: "/ para sempre",
        month: "/ mês",
        contactSales: "Falar com Vendas",
        aiWelcome: "Olá! Sou a IA do FluxFunnel. Posso ajudar a auditar sua estratégia. O que deseja analisar?",
        aiAuditBtn: "Auditar Funil",
        aiSimulateBtn: "Simular Tráfico",
        aiImproveBtn: "Melhorar Conversão",
        roadmapTitle: "Roadmap Público",
        roadmapDesc: "Ajude-nos a construir o melhor construtor de funis. Vote em funcionalidades ou sugira melhorias.",
        feedbackBtn: "Enviar Sugestão",
        statusPlanned: "Planejado",
        statusInProgress: "Em Progreso",
        statusCompleted: "Concluído",
        statusPending: "Em Análise",
        feedbackTypeFeature: "Nova Funcionalidade",
        feedbackTypeBug: "Bug / Erro",
        feedbackTypeImprovement: "Melhoria",
        feedbackTypeOther: "Outro",
        submitFeedbackTitle: "Enviar Feedback",
        feedbackTitleLabel: "Título",
        feedbackDescLabel: "Descrição",
        feedbackTypeLabel: "Tipo",
        submitBtn: "Enviar",
        backToHome: "Voltar para Início",
        adminDashboard: "Painel Mestre (SAS)",
        searchPlaceholder: "Buscar feedbacks...",
        filterByType: "Filtrar por Tipo",
        filterByStatus: "Filtrar por Status",
        allTypes: "Todos os Tipos",
        allStatus: "Todos os Status",
        noFeedbackFound: "Nenhum feedback encontrado.",
        noFeedbackDesc: "Seja o primeiro a sugerir algo nesta categoria!",
        loginRequiredTitle: "Login Necessário",
        loginRequiredMsg: "Você precisa estar conectado ao sistema para enviar sugestões ou votar. Entre com sua conta Google ou email/senha.",
        loginBtn: "Fazer Login / Cadastrar",
        continueWithGoogle: "Entrar com Google",
        adminOverview: "Visão Geral",
        adminUsers: "Usuários",
        adminPlans: "Planos",
        adminMetrics: "Métricas & Receita",
        adminFeedback: "Roadmap & Feedback",
        adminTotalUsers: "Total Usuários",
        adminActiveUsers: "Usuários Ativos",
        adminInactiveUsers: "Inativos",
        adminBannedUsers: "Banidos",
        adminMRR: "Receita Mensal (MRR)",
        adminPlanDistribution: "Distribuição de Planos",
        adminEditUser: "Editar Usuário",
        adminSaveUser: "Salvar Usuário",
        adminDisableUser: "Desativar",
        adminEnableUser: "Ativar",
        adminDeleteUser: "Banir/Excluir",
        adminEditPlan: "Editar Plano",
        adminCreatePlan: "Novo Plano",
        adminPrice: "Preço Mensal",
        adminPriceYearly: "Preço Anual",
        adminDeletePlan: "Excluir Plano",
        adminLimits: "Limites (Projetos/Nós)",
        adminActions: "Ações",
        adminUserStatus: "Status",
        adminLastLogin: "Último Login",
        adminImpersonate: "Acessar Conta",
        adminRecentActivity: "Atividade Recente",
        adminRevenueTrend: "Tendência de Receita",
        adminFeaturesList: "Features (Separadas por vírgula)",
        loginRequiredMsgOld: "Você precisa estar conectado para interagir. Deseja fazer login agora?",
        viewingMode: "Modo de Visualização • Edição Desativada",

        // MARKETPLACE
        marketplace: "Marketplace",
        marketplaceDesc: "Compartilhe e descubra estratégias da nossa comunidade.",
        shareTemplate: "Compartilhar no Marketplace",
        shareTemplateDesc: "Sua estratégia passará por uma curadoria antes de ficar pública.",
        topRated: "Melhores Avaliados",
        mostDownloaded: "Mais Baixados",
        allCategories: "Todas Categorias",
        searchTemplates: "Buscar estratégias...",
        downloadTemplate: "Baixar Estratégia",
        templateRating: "Avaliação",
        publishSuccess: "Enviado para aprovação!",
        moderationPending: "Aguardando moderação",
        moderationApproved: "Aprovado",
        moderationRejected: "Rejeitado",
        ratingRequired: "Avalie este template",
        premiumOnly: "Recurso Exclusivo Premium",
        reportTemplate: "Denunciar Conteúdo",
        quickLook: "Visão Rápida"
    },
    en: {
        heroTitle: "Your Strategy Deserves\nMore Than a Scribble.",
        heroDesc: "Professionalize your planning. Transform loose ideas into organized visual maps, ready to present, teach, or execute.",
        startFree: "Create My First Map",
        watchDemo: "Watch How It Works",
        features: "Benefits",
        pricing: "Plans",
        signIn: "Sign In",
        getStarted: "Get Started Free",
        problemTitle: "Benefits",
        problemDesc: "Why choose FluxFunnel?",
        problem1Title: "Instant Clarity",
        problem1Desc: "See your entire strategy in a single visual map.",
        problem2Title: "Professional Planning",
        problem2Desc: "Stop using paper, whiteboards, or improvised tools.",
        problem3Title: "Present and Teach",
        problem3Desc: "Explain your strategy to clients, partners, or team in minutes.",
        problem4Title: "More Organization",
        problem4Desc: "Transform loose ideas into well-defined processes.",
        solutionTitle: "What is FluxFunnel?",
        solutionDesc: "FluxFunnel is a visual funnel and strategy builder designed for those who need to see, organize, and explain marketing and sales processes.",
        solution1Title: "Visual Canvas",
        solution1Desc: "Drag and drop without code. Build everything visually.",
        solution2Title: "No Complex Integrations",
        solution2Desc: "100% focused on visual planning and organization.",
        solution3Title: "Complete Library",
        solution3Desc: "Ads, Pages, E-mail, WhatsApp, and much more.",
        useCasesTitle: "Who Is It For?",
        useCase1Title: "Managers & Owners",
        useCase1Desc: "Business owners, Marketing Managers, and Sales Managers.",
        useCase2Title: "Service Providers",
        useCase2Desc: "Agencies, Consultants, and Sales Teams.",
        useCase3Title: "Educators",
        useCase3Desc: "Digital Producers and Teachers who need didactics.",
        howItWorks: "How It Works",
        howItWorksSub: "From chaos to order in simple steps.",
        step1Title: "1. Create & Drag",
        step1Desc: "Create a new map and drag elements (Ads, Pages, WhatsApp) to the canvas.",
        step2Title: "2. Connect Flows",
        step2Desc: "Connect the dots to define the customer journey and visualize the whole strategy.",
        step3Title: "3. Plan & Execute",
        step3Desc: "Use the map to present, validate ideas, or guide implementation.",
        faqTitle: "Common Questions",
        faq1Q: "Is it hard to use?",
        faq1A: "No. FluxFunnel was created for anyone, even without technical knowledge. It is intuitive and 100% visual.",
        faq2Q: "Do I need to integrate with any ad account?",
        faq2A: "No. The focus is 100% on visual planning and organization. No boring technical configurations or complex integrations.",
        faq3Q: "What are the limits of the free plan?",
        faq3A: "You can create 1 active project, with up to 20 elements in the flow and access to basic icons.",
        ctaFinalTitle: "Organize Your Ideas Today",
        ctaFinalDesc: "Create your free account and draw your first professional flow in minutes.",
        ctaFinalBtn: "Start Now - It's Free",
        upgradeSuccess: "Plan updated successfully! Enjoy Premium features.",
        noCreditCard: "No credit card required",
        freeTrialDays: "Lifetime Free Plan",
        monthly: "Monthly",
        yearly: "Yearly",
        simplePricing: "Simple Plans",
        mostPopular: "RECOMMENDED",
        pricingFreeFeat1: "1 Active Project",
        pricingFreeFeat2: "20 Elements in Flow",
        pricingFreeFeat3: "Basic Icons",
        pricingFreeFeat4: "Presentation Mode",
        pricingFreeFeat5: "Email Support",
        pricingFreeFeat6: "Dark & Light Mode",
        pricingProFeat1: "5 Active Projects",
        pricingProFeat2: "100 Elements in Flow",
        pricingProFeat3: "Complete Library",
        pricingProFeat4: "Sticky Notes",
        pricingProFeat5: "Save Templates",
        pricingProFeat6: "Dedicated Support",
        pricingPremiumFeat1: "Unlimited Projects",
        pricingPremiumFeat2: "Unlimited Elements",
        pricingPremiumFeat3: "Team Collab (3)",
        pricingPremiumFeat4: "AI: Strategy Audit (Beta)",
        pricingPremiumFeat5: "Share Link",
        pricingPremiumFeat6: "Priority Support",
        planBtnFree: "Start for Free",
        planBtnPro: "Subscribe Now",
        planBtnPremium: "Contact Sales",
        footerProduct: "Product",
        footerCompany: "Company",
        footerLegal: "Legal",
        footerTagline: "Where great strategies are drawn.",
        footerLinkBuilder: "Builder",
        footerLinkSims: "Gallery",
        footerLinkIntegrations: "Icons",
        footerLinkRoadmap: "Roadmap & Feedback",
        footerLinkAbout: "About",
        footerLinkBlog: "Blog",
        footerLinkCareers: "Careers",
        footerLinkPrivacy: "Privacy",
        footerLinkTerms: "Terms",
        footerRights: "FluxFunnel Inc.",
        startBuilding: "Start organizing now.",
        testimonialsNav: "Who Is It For",
        faqNav: "FAQ",
        pricingNav: "Pricing",
        featuresNav: "Features",
        trafficSources: "Traffic Sources",
        communication: "Communication",
        funnelPages: "Funnel Pages",
        opsLogic: "Ops & Logic",
        componentLib: "Library",
        dragElements: "Drag to canvas",
        projects: "Projects",
        myProjects: "My Projects",
        maps: "Maps",
        team: "Team",
        upgrade: "Upgrade",
        settings: "Settings",
        signOut: "Sign Out",
        editFunnel: "Edit Funnel",
        present: "Present",
        lastSaved: "Saved at",
        save: "Save",
        unsavedChanges: "• Unsaved",
        saved: "Saved",
        noProjectSelected: "No project selected",
        backToProjects: "Back to Projects",
        createMapTitle: "Create New Map",
        projectName: "Project Name",
        cancel: "Cancel",
        createMapBtn: "Create Map",
        unsavedModalTitle: "Unsaved Changes",
        unsavedModalDesc: "You have pending edits. What do you want to do before leaving?",
        saveAndExit: "Save and Exit",
        discardChanges: "Discard Changes",
        keepEditing: "Cancel (Keep Editing)",
        projectsDesc: "Manage your maps and educational flows.",
        newProject: "New Project",
        createVisualShortcut: "Create New Map",
        editedAt: "Edited at",
        elementsCount: "Elements",
        openBtn: "Open",
        deleteBtn: "Delete",
        noMapsCreated: "No maps created",
        startOrganizingNow: "Start organizing your ideas right now.",
        createFirstProject: "Create my first project",
        chooseTemplate: "Choose a Template",
        blankCanvas: "Blank Canvas",
        blankCanvasDesc: "Start from scratch with a clean slate.",
        templateVSL: "VSL Funnel",
        templateWebinar: "Webinar Funnel",
        templateTripwire: "Tripwire Funnel",
        templateLaunch: "Seed Launch",
        saveAsTemplate: "Save as Template",
        myTemplates: "My Templates",
        systemTemplates: "System Templates",
        templateSaved: "Template saved successfully!",
        manageAccount: "Manage your account, preferences, and subscription.",
        tabProfile: "My Profile",
        tabPreferences: "Preferences",
        tabPlan: "Plan & Billing",
        tabSecurity: "Security",
        tabNotifications: "Notifications",
        personalInfo: "Personal Information",
        yourPhoto: "Your Photo",
        photoDesc: "This will be displayed on your profile.",
        saveChanges: "Save Changes",
        saving: "Saving...",
        appearanceLang: "Appearance & Language",
        darkMode: "Dark Mode",
        darkModeDesc: "Switch between light and dark themes.",
        systemLang: "System Language",
        currentPlan: "Current Plan",
        autoRenewal: "Auto-renewal active",
        billingHistory: "Billing History",
        tableDate: "Date",
        tableDesc: "Description",
        tableAmount: "Amount",
        tableStatus: "Status",
        noBilling: "No billing history (Free Plan)",
        paid: "Paid",
        accountSecurity: "Account Security",
        currentPwd: "Current Password",
        newPwd: "New Password",
        confirmPwd: "Confirm New Password",
        updatePwd: "Update Password",
        dangerZone: "Danger Zone",
        deleteAccount: "Delete Account",
        deleteWarning: "Deleting your account is irreversible. All maps and data will be lost.",
        companyName: "Company Name",
        jobTitle: "Job Title",
        paymentMethod: "Payment Method",
        cardEnding: "ending in",
        expires: "Expires",
        updateMethod: "Update",
        usageLimit: "Plan Usage",
        projectsUsed: "Projects Created",
        nodesUsed: "Elements in Flow",
        upgradeToIncrease: "Upgrade to increase limits",
        activeSessions: "Active Sessions",
        currentSession: "This device",
        twoFactor: "Two-Factor Authentication (2FA)",
        twoFactorDesc: "Add an extra layer of security to your account.",
        enable: "Enable",
        disable: "Disable",
        marketingEmails: "Marketing Emails",
        marketingEmailsDesc: "Receive tips, offers, and product news.",
        securityEmails: "Security Alerts",
        securityEmailsDesc: "Receive alerts about suspicious logins.",
        welcomeBack: "Welcome back",
        createAccount: "Create Account",
        enterDetails: "Enter your details below",
        fullName: "Full Name",
        emailAddr: "Email",
        password: "Password",
        dontHaveAccount: "Don't have an account?",
        alreadyHaveAccount: "Already have an account?",
        starter: "Free",
        pro: "Pro",
        agency: "Premium",
        forever: "/ forever",
        month: "/ month",
        contactSales: "Contact Sales",
        aiWelcome: "Hello! I am FluxFunnel AI. I can help audit your strategy. What would you like to analyze?",
        aiAuditBtn: "Audit Funnel",
        aiSimulateBtn: "Simulate Traffic",
        aiImproveBtn: "Improve Conversion",
        roadmapTitle: "Public Roadmap",
        roadmapDesc: "Help us build the best funnel builder. Vote on features or suggest improvements.",
        feedbackBtn: "Submit Suggestion",
        statusPlanned: "Planned",
        statusInProgress: "In Progress",
        statusCompleted: "Completed",
        statusPending: "Pending Review",
        feedbackTypeFeature: "New Feature",
        feedbackTypeBug: "Bug / Error",
        feedbackTypeImprovement: "Improvement",
        feedbackTypeOther: "Other",
        submitFeedbackTitle: "Submit Feedback",
        feedbackTitleLabel: "Title",
        feedbackDescLabel: "Description",
        feedbackTypeLabel: "Type",
        submitBtn: "Submit",
        backToHome: "Back to Home",
        adminDashboard: "Master Dashboard (SAS)",
        searchPlaceholder: "Search feedback...",
        filterByType: "Filter by Type",
        filterByStatus: "Filter by Status",
        allTypes: "All Types",
        allStatus: "All Status",
        noFeedbackFound: "No feedback found.",
        noFeedbackDesc: "Be the first to suggest something in this category!",
        loginRequiredTitle: "Login Required",
        loginRequiredMsg: "You need to be connected to the system to submit suggestions or vote. Sign in with Google or email/password.",
        loginBtn: "Login / Sign Up",
        continueWithGoogle: "Continue with Google",
        adminOverview: "Overview",
        adminUsers: "Users",
        adminPlans: "Plans",
        adminMetrics: "Metrics & Revenue",
        adminFeedback: "Roadmap & Feedback",
        adminTotalUsers: "Total Users",
        adminActiveUsers: "Active Users",
        adminInactiveUsers: "Inactive",
        adminBannedUsers: "Banned",
        adminMRR: "Monthly Revenue (MRR)",
        adminPlanDistribution: "Plan Distribution",
        adminEditUser: "Edit User",
        adminSaveUser: "Save User",
        adminDisableUser: "Disable",
        adminEnableUser: "Enable",
        adminDeleteUser: "Ban/Delete",
        adminEditPlan: "Edit Plan",
        adminCreatePlan: "New Plan",
        adminPrice: "Monthly Price",
        adminPriceYearly: "Yearly Price",
        adminDeletePlan: "Delete Plan",
        adminLimits: "Limits (Projects/Nodes)",
        adminActions: "Actions",
        adminUserStatus: "Status",
        adminLastLogin: "Last Login",
        adminImpersonate: "Impersonate",
        adminRecentActivity: "Recent Activity",
        adminRevenueTrend: "Revenue Trend",
        adminFeaturesList: "Features (Comma separated)",
        loginRequiredMsgOld: "You must be logged in to interact. Do you want to sign in now?",
        viewingMode: "Viewing Mode • Editing Disabled",

        // MARKETPLACE EN
        marketplace: "Marketplace",
        marketplaceDesc: "Share and discover strategies from our community.",
        shareTemplate: "Share to Marketplace",
        shareTemplateDesc: "Your strategy will be curated before going public.",
        topRated: "Top Rated",
        mostDownloaded: "Most Downloaded",
        allCategories: "All Categories",
        searchTemplates: "Search strategies...",
        downloadTemplate: "Download Strategy",
        templateRating: "Rating",
        publishSuccess: "Sent for approval!",
        moderationPending: "Awaiting moderation",
        moderationApproved: "Approved",
        moderationRejected: "Rejected",
        ratingRequired: "Rate this template",
        premiumOnly: "Premium Exclusive Feature",
        reportTemplate: "Report Content",
        quickLook: "Quick Look"
    },
    es: {
        heroTitle: "Tu Estrategia Merece\nMás que un Garabato.",
        heroDesc: "Profesionaliza tu planificación. Transforma ideas sueltas en mapas visuais organizados, listos para presentar, enseñar o ejecutar.",
        startFree: "Crear Mi Primer Mapa",
        watchDemo: "Ver Cómo Funciona",
        features: "Beneficios",
        pricing: "Planes",
        signIn: "Entrar",
        getStarted: "Empezar Gratis",
        problemTitle: "Beneficios",
        problemDesc: "¿Por qué elegir FluxFunnel?",
        problem1Title: "Claridad Inmediata",
        problem1Desc: "Ve toda tu estrategia en un único mapa visual.",
        problem2Title: "Planificación Profesional",
        problem2Desc: "Deja de usar papel, pizarra o herramientas improvisadas.",
        problem3Title: "Presenta y Enseña",
        problem3Desc: "Explica tu estrategia a clientes, socios o equipo en minutos.",
        problem4Title: "Más Organización",
        problem4Desc: "Transforma ideas sueltas en procesos bien definidos.",
        solutionTitle: "¿Qué es FluxFunnel?",
        solutionDesc: "FluxFunnel es un constructor visual de embudos y estrategias, creado para quien necesita ver, organizar e explicar procesos de marketing e ventas.",
        solution1Title: "Canvas Visual",
        solution1Desc: "Arrastra y suelta sin códigos. Monta todo visualmente.",
        solution2Title: "Sin Integraciones Complejas",
        solution2Desc: "Enfoque 100% en la planificación visual e organización.",
        solution3Title: "Biblioteca Completa",
        solution3Desc: "Ads, Páginas, E-mail, WhatsApp y mucho más.",
        useCasesTitle: "¿Para Quién Es?",
        useCase1Title: "Gestores y Dueños",
        useCase1Desc: "Dueños de negocios, Gestores de Marketing y Gestores Comerciais.",
        useCase2Title: "Proveedores de Servicio",
        useCase2Desc: "Agencias, Consultores e Equipos de Ventas.",
        useCase3Title: "Educadores",
        useCase3Desc: "Productores Digitales y Profesores que necesitan didáctica.",
        howItWorks: "Cómo Funciona",
        howItWorksSub: "Del caos al orden en pasos simples.",
        step1Title: "1. Crea y Arrastra",
        step1Desc: "Crea un nuevo mapa y arrastra elementos (Ads, Páginas, WhatsApp) al canvas.",
        step2Title: "2. Conecta los Flujos",
        step2Desc: "Une los puntos para definir el viaje del cliente y visualiza toda la estrategia.",
        step3Title: "3. Planifica y Ejecuta",
        step3Desc: "Usa el mapa para presentar, validar ideas o guiar la implementación.",
        faqTitle: "Dudas Comunes",
        faq1Q: "¿Es difícil de usar?",
        faq1A: "No. FluxFunnel fue creado para cualquier persona, incluso sin conocimiento técnico. Es intuitivo y 100% visual.",
        faq2Q: "¿Necesito integrar con alguna cuenta de anuncios?",
        faq2A: "No. El enfoque é 100% en la planificación visual y organización. Sin configuraciones técnicas aburridas o integraciones complejas.",
        faq3Q: "¿Cuáles son los límites del plan gratuito?",
        faq3A: "Puedes crear 1 proyecto activo, con hasta 20 elementos en el flujo y acceso a los iconos básicos.",
        ctaFinalTitle: "Organiza Tus Ideas Hoy",
        ctaFinalDesc: "Crea tu cuenta gratuita y dibuja tu primer flujo profesional en minutos.",
        ctaFinalBtn: "Empezar Ahora - Es Gratis",
        upgradeSuccess: "¡Plan actualizado con éxito! Disfruta de las funciones Premium.",
        noCreditCard: "Sin tarjeta de crédito",
        freeTrialDays: "Plan Gratuito Vitalicio",
        monthly: "Mensual",
        yearly: "Anual",
        simplePricing: "Planes Simples",
        mostPopular: "RECOMENDADO",
        pricingFreeFeat1: "1 Proyecto Activo",
        pricingFreeFeat2: "20 Elements en Flujo",
        pricingFreeFeat3: "Iconos Básicos",
        pricingFreeFeat4: "Modo Presentación",
        pricingFreeFeat5: "Soporte vía Email",
        pricingFreeFeat6: "Modo Oscuro & Claro",
        pricingProFeat1: "5 Proyectos Activos",
        pricingProFeat2: "100 Elementos en Flujo",
        pricingProFeat3: "Biblioteca Completa",
        pricingProFeat4: "Notas Adhesivas",
        pricingProFeat5: "Guardar Plantillas",
        pricingProFeat6: "Soporte Dedicado",
        pricingPremiumFeat1: "Proyectos Ilimitados",
        pricingPremiumFeat2: "Elementos Ilimitados",
        pricingPremiumFeat3: "Equipo (3 Personas)",
        pricingPremiumFeat4: "IA: Auditoría de Estrategia (Beta)",
        pricingPremiumFeat5: "Compartir Link",
        pricingPremiumFeat6: "Soporte Prioritario",
        planBtnFree: "Empezar Gratis",
        planBtnPro: "Suscribirse Ahora",
        planBtnPremium: "Hablar con Ventas",
        footerProduct: "Producto",
        footerCompany: "Empresa",
        footerLegal: "Legal",
        footerTagline: "Donde se dibujan las grandes estrategias.",
        footerLinkBuilder: "Constructor",
        footerLinkSims: "Galería",
        footerLinkIntegrations: "Iconos",
        footerLinkRoadmap: "Roadmap y Feedback",
        footerLinkAbout: "Sobre",
        footerLinkBlog: "Blog",
        footerLinkCareers: "Carreras",
        footerLinkPrivacy: "Privacidad",
        footerLinkTerms: "Términos",
        footerRights: "FluxFunnel Inc.",
        startBuilding: "Empieza a organizar ahora.",
        testimonialsNav: "Para Quién Es",
        faqNav: "Dudas",
        pricingNav: "Precios",
        featuresNav: "Beneficios",
        trafficSources: "Fuentes de Tráfico",
        communication: "Comunicación",
        funnelPages: "Páginas del Embudo",
        opsLogic: "Ops y Lógica",
        componentLib: "Biblioteca",
        dragElements: "Arrastra al canvas",
        projects: "Proyectos",
        myProjects: "Mis Proyectos",
        maps: "Mapas",
        team: "Equipo",
        upgrade: "Mejorar",
        settings: "Configuraciones",
        signOut: "Salir",
        editFunnel: "Editar Embudo",
        present: "Presentar",
        lastSaved: "Guardado a las",
        save: "Guardar",
        unsavedChanges: "• No Guardado",
        saved: "Guardado",
        noProjectSelected: "Ningún proyecto seleccionado",
        backToProjects: "Volver a Proyectos",
        createMapTitle: "Crear Nuevo Mapa",
        projectName: "Nombre del Proyecto",
        cancel: "Cancelar",
        createMapBtn: "Crear Mapa",
        unsavedModalTitle: "Cambios no guardados",
        unsavedModalDesc: "Tienes ediciones pendientes. ¿Qué deseas hacer antes de salir?",
        saveAndExit: "Guardar y Salir",
        discardChanges: "Descartar cambios",
        keepEditing: "Cancelar (Seguir editando)",
        projectsDesc: "Gestiona tus mapas y flujos educativos.",
        newProject: "Nuevo Projeto",
        createVisualShortcut: "Crear Nuevo Mapa",
        editedAt: "Editado el",
        elementsCount: "Elementos",
        openBtn: "Abrir",
        deleteBtn: "Eliminar",
        noMapsCreated: "Ningún mapa creado",
        startOrganizingNow: "Empieza a organizar tus ideas ahora mismo.",
        createFirstProject: "Crear mi primer projeto",
        chooseTemplate: "Elige una Plantilla",
        blankCanvas: "Lienzo en Blanco",
        blankCanvasDesc: "Empieza desde cero con un lienzo limpio.",
        templateVSL: "Embudo VSL",
        templateWebinar: "Embudo Webinar",
        templateTripwire: "Embudo Tripwire",
        templateLaunch: "Lanzamiento Semilla",
        saveAsTemplate: "Guardar como Plantilla",
        myTemplates: "Mis Plantillas",
        systemTemplates: "Plantillas del Sistema",
        templateSaved: "¡Plantilla guardada con éxito!",
        manageAccount: "Gestiona tu cuenta, preferencias y suscripción.",
        tabProfile: "Mi Perfil",
        tabPreferences: "Preferencias",
        tabPlan: "Planes y Facturación",
        tabSecurity: "Seguridad",
        tabNotifications: "Notificaciones",
        personalInfo: "Información Personal",
        yourPhoto: "Tu Foto",
        photoDesc: "Esto se mostrará en tu perfil.",
        saveChanges: "Guardar Cambios",
        saving: "Guardando...",
        appearanceLang: "Apariencia e Idioma",
        darkMode: "Modo Oscuro",
        darkModeDesc: "Alterna entre temas claro e oscuro.",
        systemLang: "Idioma del Sistema",
        currentPlan: "Plan Actual",
        autoRenewal: "Renovación automática activa",
        billingHistory: "Historial de Facturación",
        tableDate: "Fecha",
        tableDesc: "Descripción",
        tableAmount: "Importe",
        tableStatus: "Estado",
        noBilling: "Sin historial de cobros (Plan Gratuito)",
        paid: "Pagado",
        accountSecurity: "Seguridad de la Cuenta",
        currentPwd: "Contraseña Actual",
        newPwd: "Nueva Contraseña",
        confirmPwd: "Confirmar Nueva Contraseña",
        updatePwd: "Actualizar Contraseña",
        dangerZone: "Zona de Peligro",
        deleteAccount: "Eliminar Cuenta",
        deleteWarning: "La eliminación de tu cuenta es irreversible. Se perderán todos tus mapas y datos.",
        companyName: "Nombre de la Empresa",
        jobTitle: "Cargo / Puesto",
        paymentMethod: "Método de Pago",
        cardEnding: "terminado en",
        expires: "Expira en",
        updateMethod: "Actualizar",
        usageLimit: "Uso del Plan",
        projectsUsed: "Proyectos Creados",
        nodesUsed: "Elementos en Flujo",
        upgradeToIncrease: "Actualizar para aumentar límites",
        activeSessions: "Sesiones Activas",
        currentSession: "Este dispositivo",
        twoFactor: "Autenticación de Dos Factores (2FA)",
        twoFactorDesc: "Añade una capa extra de seguridad a tu cuenta.",
        enable: "Activar",
        disable: "Desactivar",
        marketingEmails: "Correos de Marketing",
        marketingEmailsDesc: "Recibe consejos, ofertas y noticias del producto.",
        securityEmails: "Alertas de Seguridad",
        securityEmailsDesc: "Recibe avisos sobre inicios de sesión sospechosos.",
        welcomeBack: "Bienvenido de nuevo",
        createAccount: "Crear Cuenta",
        enterDetails: "Introduce tus datos abajo",
        fullName: "Nombre Completo",
        emailAddr: "E-mail",
        password: "Contraseña",
        dontHaveAccount: "¿No tienes una cuenta?",
        alreadyHaveAccount: "¿Ya tienes una cuenta?",
        starter: "Gratis",
        pro: "Pro",
        agency: "Premium",
        forever: "/ para sempre",
        month: "/ mes",
        contactSales: "Hablar con Ventas",
        aiWelcome: "¡Hola! Soy la IA de FluxFunnel. Puedo ayudar a auditar tu estrategia. ¿Qué deseas analizar?",
        aiAuditBtn: "Auditar Embudo",
        aiSimulateBtn: "Simular Tráfico",
        aiImproveBtn: "Mejorar Conversión",
        roadmapTitle: "Roadmap Público",
        roadmapDesc: "Ayúdanos a construir el mejor constructor de embudos. Vota por funcionalidades o sugiere mejoras.",
        feedbackBtn: "Enviar Sugerencia",
        statusPlanned: "Planeado",
        statusInProgress: "En Progreso",
        statusCompleted: "Completado",
        statusPending: "Pendiente",
        feedbackTypeFeature: "Nueva Funcionalidade",
        feedbackTypeBug: "Bug / Error",
        feedbackTypeImprovement: "Mejora",
        feedbackTypeOther: "Otro",
        submitFeedbackTitle: "Enviar Feedback",
        feedbackTitleLabel: "Título",
        feedbackDescLabel: "Descripción",
        feedbackTypeLabel: "Tipo",
        submitBtn: "Enviar",
        backToHome: "Voltar a Inicio",
        adminDashboard: "Panel Maestro (SAS)",
        searchPlaceholder: "Buscar feedbacks...",
        filterByType: "Filtrar por Tipo",
        filterByStatus: "Filtrar por Estado",
        allTypes: "Todos los Tipos",
        allStatus: "Todos os Estados",
        noFeedbackFound: "Ningún feedback encontrado.",
        noFeedbackDesc: "¡Sé el primero en sugerir algo en esta categoría!",
        loginRequiredTitle: "Inicio de Sesión Requerido",
        loginRequiredMsg: "Necesitas estar conectado al sistema para enviar sugerencias o votar. Inicia sesión con tu cuenta de Google o email/contraseña.",
        loginBtn: "Iniciar Sesión / Registrarse",
        continueWithGoogle: "Continuar con Google",
        adminOverview: "Visión General",
        adminUsers: "Usuarios",
        adminPlans: "Planes",
        adminMetrics: "Métricas e Ingresos",
        adminFeedback: "Roadmap y Feedback",
        adminTotalUsers: "Total Usuarios",
        adminActiveUsers: "Usuarios Activos",
        adminInactiveUsers: "Inactivos",
        adminBannedUsers: "Baneados",
        adminMRR: "Ingresos Mensuales (MRR)",
        adminPlanDistribution: "Distribución de Planes",
        adminEditUser: "Editar Usuario",
        adminSaveUser: "Guardar Usuario",
        adminDisableUser: "Desativar",
        adminEnableUser: "Activar",
        adminDeleteUser: "Banear/Eliminar",
        adminEditPlan: "Editar Plano",
        adminCreatePlan: "Nuevo Plano",
        adminPrice: "Precio Mensual",
        adminPriceYearly: "Precio Anual",
        adminDeletePlan: "Eliminar Plan",
        adminLimits: "Límites (Projetos/Nodos)",
        adminActions: "Acciones",
        adminUserStatus: "Estado",
        adminLastLogin: "Último Acceso",
        adminImpersonate: "Acceder Cuenta",
        adminRecentActivity: "Actividad Reciente",
        adminRevenueTrend: "Tendencia de Ingresos",
        adminFeaturesList: "Características (Separadas por coma)",
        loginRequiredMsgOld: "Debes iniciar sesión para interactuar. ¿Quieres iniciar sesión ahora?",
        viewingMode: "Modo de Visualização • Edição Desativada",

        // MARKETPLACE ES
        marketplace: "Marketplace",
        marketplaceDesc: "Comparte y descubre estrategias de nuestra comunidad.",
        shareTemplate: "Compartir en Marketplace",
        shareTemplateDesc: "Tu estrategia pasará por una curaduría antes de ser pública.",
        topRated: "Mejor Calificados",
        mostDownloaded: "Más Descargados",
        allCategories: "Todas las Categorías",
        searchTemplates: "Buscar estrategias...",
        downloadTemplate: "Descargar Estrategia",
        templateRating: "Calificación",
        publishSuccess: "¡Enviado para aprobación!",
        moderationPending: "Esperando moderación",
        moderationApproved: "Aprobado",
        moderationRejected: "Rechazado",
        ratingRequired: "Califica esta plantilla",
        premiumOnly: "Función Exclusiva Premium",
        reportTemplate: "Denunciar Contenido",
        quickLook: "Vista Rápida"
    }
};

export enum NODE_CATEGORY {
    TRAFFIC = 'TRAFFIC',
    CHANNEL = 'CHANNEL',
    PAGE = 'PAGE',
    LOGIC = 'LOGIC'
}

export const NODE_CONFIG: Record<NodeType, {
    label: string;
    icon: React.ReactNode;
    category: NODE_CATEGORY;
    bg: string;
    borderColor: string;
    isPro?: boolean;
}> = {
    [NodeType.LANDING_PAGE]: { label: 'Página de Captura', icon: <LayoutTemplate />, category: NODE_CATEGORY.PAGE, bg: 'bg-blue-500', borderColor: 'border-blue-600' },
    [NodeType.OPTIN_PAGE]: { label: 'Página de Opt-in', icon: <FormInput />, category: NODE_CATEGORY.PAGE, bg: 'bg-emerald-500', borderColor: 'border-emerald-600' },
    [NodeType.CHECKOUT]: { label: 'Checkout', icon: <ShoppingCart />, category: NODE_CATEGORY.PAGE, bg: 'bg-slate-900', borderColor: 'border-slate-950' },
    [NodeType.ORDER_PAGE]: { label: 'Página de Vendas', icon: <FileText />, category: NODE_CATEGORY.PAGE, bg: 'bg-violet-600', borderColor: 'border-violet-700' },
    [NodeType.VSL]: { label: 'Página VSL', icon: <PlayCircle />, category: NODE_CATEGORY.PAGE, bg: 'bg-orange-500', borderColor: 'border-orange-600' },
    [NodeType.UPSELL]: { label: 'Upsell', icon: <ArrowDownCircle className="rotate-180" />, category: NODE_CATEGORY.PAGE, bg: 'bg-green-600', borderColor: 'border-green-700', isPro: true },
    [NodeType.DOWNSELL]: { label: 'Downsell', icon: <ArrowDownCircle />, category: NODE_CATEGORY.PAGE, bg: 'bg-slate-500', borderColor: 'border-slate-600', isPro: true },
    [NodeType.THANK_YOU]: { label: 'Obrigado', icon: <CheckCircle />, category: NODE_CATEGORY.PAGE, bg: 'bg-green-500', borderColor: 'border-green-600' },
    [NodeType.WEBINAR]: { label: 'Webinar', icon: <MonitorPlay />, category: NODE_CATEGORY.PAGE, bg: 'bg-indigo-600', borderColor: 'border-indigo-700', isPro: true },
    [NodeType.LIVE_WEBINAR]: { label: 'Live Stream', icon: <Radio />, category: NODE_CATEGORY.PAGE, bg: 'bg-red-600', borderColor: 'border-red-700', isPro: true },
    [NodeType.BLOG]: { label: 'Blog Post', icon: <FileText />, category: NODE_CATEGORY.PAGE, bg: 'bg-slate-600', borderColor: 'border-slate-700', isPro: true },
    [NodeType.QUIZ]: { label: 'Quiz', icon: <HelpCircle />, category: NODE_CATEGORY.PAGE, bg: 'bg-pink-500', borderColor: 'border-pink-600', isPro: true },
    [NodeType.MEMBERSHIP_AREA]: { label: 'Área de Membros', icon: <Library />, category: NODE_CATEGORY.PAGE, bg: 'bg-cyan-600', borderColor: 'border-cyan-700', isPro: true },
    [NodeType.DOWNLOAD_PAGE]: { label: 'Download', icon: <Download />, category: NODE_CATEGORY.PAGE, bg: 'bg-teal-500', borderColor: 'border-teal-600', isPro: true },
    [NodeType.CALENDAR_PAGE]: { label: 'Agendamento', icon: <CalendarDays />, category: NODE_CATEGORY.PAGE, bg: 'bg-blue-600', borderColor: 'border-blue-700', isPro: true },
    [NodeType.GENERIC_PAGE]: { label: 'Página Genérica', icon: <AppWindow />, category: NODE_CATEGORY.PAGE, bg: 'bg-slate-400', borderColor: 'border-slate-500', isPro: true },
    [NodeType.POPUP]: { label: 'Pop-up', icon: <AppWindow />, category: NODE_CATEGORY.PAGE, bg: 'bg-purple-500', borderColor: 'border-purple-600', isPro: true },
    [NodeType.SYSTEM_PAGE]: { label: 'Sistema / App', icon: <Server />, category: NODE_CATEGORY.PAGE, bg: 'bg-slate-700', borderColor: 'border-slate-800', isPro: true },
    [NodeType.ECOMMERCE_PAGE]: { label: 'Loja Virtual', icon: <Store />, category: NODE_CATEGORY.PAGE, bg: 'bg-rose-600', borderColor: 'border-rose-700', isPro: true },
    [NodeType.META_ADS]: { label: 'Meta Ads', icon: <Infinity />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-blue-600', borderColor: 'border-blue-700' },
    [NodeType.FACEBOOK_ADS]: { label: 'Facebook', icon: <Facebook className="mr-[2px]" />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-blue-700', borderColor: 'border-blue-800' },
    [NodeType.GOOGLE_ADS]: { label: 'Google Ads', icon: <Search />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-blue-500', borderColor: 'border-blue-600' },
    [NodeType.GOOGLE_SEARCH]: { label: 'SEO / Orgânico', icon: <Search />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-green-600', borderColor: 'border-green-700', isPro: true },
    [NodeType.BING_ADS]: { label: 'Bing Ads', icon: <Globe />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-teal-600', borderColor: 'border-teal-700', isPro: true },
    [NodeType.TIKTOK_ADS]: { label: 'TikTok', icon: <Music />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-black', borderColor: 'border-slate-800', isPro: true },
    [NodeType.INSTAGRAM]: { label: 'Instagram', icon: <Instagram />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-pink-600', borderColor: 'border-pink-700' },
    [NodeType.YOUTUBE]: { label: 'YouTube', icon: <Youtube />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-red-600', borderColor: 'border-red-700' },
    [NodeType.PINTEREST]: { label: 'Pinterest', icon: <Pin />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-red-600', borderColor: 'border-red-700', isPro: true },
    [NodeType.KWAI]: { label: 'Kwai', icon: <Smartphone />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-orange-500', borderColor: 'border-orange-600', isPro: true },
    [NodeType.TWITCH]: { label: 'Twitch', icon: <Twitch />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-purple-600', borderColor: 'border-purple-700', isPro: true },
    [NodeType.ORGANIC_SOCIAL]: { label: 'Social Orgânico', icon: <Share2 />, category: NODE_CATEGORY.TRAFFIC, bg: 'bg-green-500', borderColor: 'border-green-600', isPro: true },
    [NodeType.EMAIL]: { label: 'E-mail', icon: <Mail />, category: NODE_CATEGORY.CHANNEL, bg: 'bg-blue-500', borderColor: 'border-blue-600' },
    [NodeType.WHATSAPP]: { label: 'WhatsApp', icon: <MessageCircle />, category: NODE_CATEGORY.CHANNEL, bg: 'bg-green-500', borderColor: 'border-green-600' },
    [NodeType.SMS]: { label: 'SMS', icon: <MessageSquare />, category: NODE_CATEGORY.CHANNEL, bg: 'bg-blue-400', borderColor: 'border-blue-500', isPro: true },
    [NodeType.CALL]: { label: 'Ligação', icon: <Phone />, category: NODE_CATEGORY.CHANNEL, bg: 'bg-green-600', borderColor: 'border-green-700', isPro: true },
    [NodeType.ZOOM]: { label: 'Zoom', icon: <Video />, category: NODE_CATEGORY.CHANNEL, bg: 'bg-blue-500', borderColor: 'border-blue-600', isPro: true },
    [NodeType.GOOGLE_MEET]: { label: 'Google Meet', icon: <Video />, category: NODE_CATEGORY.CHANNEL, bg: 'bg-green-500', borderColor: 'border-green-600', isPro: true },
    [NodeType.TELEGRAM]: { label: 'Telegram', icon: <Send />, category: NODE_CATEGORY.CHANNEL, bg: 'bg-sky-500', borderColor: 'border-sky-600', isPro: true },
    [NodeType.DISCORD]: { label: 'Discord', icon: <Gamepad2 />, category: NODE_CATEGORY.CHANNEL, bg: 'bg-indigo-600', borderColor: 'border-indigo-700', isPro: true },
    [NodeType.NOTE]: { label: 'Nota', icon: <StickyNote />, category: NODE_CATEGORY.LOGIC, bg: 'bg-yellow-400', borderColor: 'border-yellow-500', isPro: true },
    [NodeType.SUBSCRIBER]: { label: 'Novo Lead', icon: <UserCheck />, category: NODE_CATEGORY.LOGIC, bg: 'bg-indigo-500', borderColor: 'border-indigo-600' },
    [NodeType.ADD_TO_CART]: { label: 'Add Carrinho', icon: <ShoppingCart />, category: NODE_CATEGORY.LOGIC, bg: 'bg-slate-500', borderColor: 'border-slate-600', isPro: true },
    [NodeType.ADD_TO_LIST]: { label: 'Add Lista', icon: <ListPlus />, category: NODE_CATEGORY.LOGIC, bg: 'bg-slate-500', borderColor: 'border-slate-600', isPro: true },
    [NodeType.CRM_PIPELINE]: { label: 'CRM', icon: <Database />, category: NODE_CATEGORY.LOGIC, bg: 'bg-slate-600', borderColor: 'border-slate-700', isPro: true },
    [NodeType.MEETING]: { label: 'Reunião', icon: <Users />, category: NODE_CATEGORY.LOGIC, bg: 'bg-blue-400', borderColor: 'border-blue-500', isPro: true },
    [NodeType.LEAD]: { label: 'Lead', icon: <UserPlus />, category: NODE_CATEGORY.LOGIC, bg: 'bg-green-500', borderColor: 'border-green-600' },
    [NodeType.REVENUE]: { label: 'Venda', icon: <CircleDollarSign />, category: NODE_CATEGORY.LOGIC, bg: 'bg-green-600', borderColor: 'border-green-700', isPro: true },
    [NodeType.PURCHASE_SUB]: { label: 'Compra/Assinatura', icon: <BadgeCheck />, category: NODE_CATEGORY.LOGIC, bg: 'bg-green-500', borderColor: 'border-green-600', isPro: true },
    [NodeType.AB_TEST]: { label: 'Teste A/B', icon: <Split />, category: NODE_CATEGORY.LOGIC, bg: 'bg-orange-500', borderColor: 'border-orange-600', isPro: true },
};

export const INITIAL_NODES: Node[] = [
    { id: '1', type: 'custom', position: { x: 250, y: 50 }, data: { label: 'Meta Ads', type: NodeType.META_ADS } },
    { id: '2', type: 'custom', position: { x: 250, y: 200 }, data: { label: 'Página de Captura', type: NodeType.LANDING_PAGE } },
    { id: '3', type: 'custom', position: { x: 250, y: 450 }, data: { label: 'Obrigado', type: NodeType.THANK_YOU } },
];

export const INITIAL_EDGES: Edge[] = [
    { id: 'e1-2', source: '1', target: '2', type: 'custom', animated: true },
    { id: 'e2-3', source: '2', target: '3', type: 'custom', animated: true },
];

export const PROJECT_TEMPLATES: Template[] = [
    {
        id: 'blank',
        labelKey: 'blankCanvas',
        descriptionKey: 'blankCanvasDesc',
        icon: <FileText />,
        nodes: [],
        edges: [],
        isPro: false
    },
    {
        id: 'vsl',
        labelKey: 'templateVSL',
        descriptionKey: 'problem1Desc',
        icon: <PlayCircle />,
        nodes: [
            { id: '1', type: 'custom', position: { x: 100, y: 100 }, data: { label: 'Meta Ads', type: NodeType.META_ADS } },
            { id: '2', type: 'custom', position: { x: 300, y: 100 }, data: { label: 'Página VSL', type: NodeType.VSL } },
            { id: '3', type: 'custom', position: { x: 500, y: 100 }, data: { label: 'Checkout', type: NodeType.CHECKOUT } },
            { id: '4', type: 'custom', position: { x: 700, y: 100 }, data: { label: 'Obrigado', type: NodeType.THANK_YOU } },
        ],
        edges: [
            { id: 'e1-2', source: '1', target: '2', type: 'custom' },
            { id: 'e2-3', source: '2', target: '3', type: 'custom' },
            { id: 'e3-4', source: '3', target: '4', type: 'custom' },
        ],
        isPro: true
    },
    {
        id: 'webinar',
        labelKey: 'templateWebinar',
        descriptionKey: 'problem2Desc',
        icon: <MonitorPlay />,
        nodes: [
            { id: '1', type: 'custom', position: { x: 100, y: 100 }, data: { label: 'Email', type: NodeType.EMAIL } },
            { id: '2', type: 'custom', position: { x: 300, y: 100 }, data: { label: 'Registro', type: NodeType.OPTIN_PAGE } },
            { id: '3', type: 'custom', position: { x: 500, y: 100 }, data: { label: 'Sala Webinar', type: NodeType.WEBINAR } },
        ],
        edges: [
            { id: 'e1-2', source: '1', target: '2', type: 'custom' },
            { id: 'e2-3', source: '2', target: '3', type: 'custom' },
        ],
        isPro: true
    }
];
